shallow_clone: true

os:
 - Visual Studio 2017

configuration:
 - Release

install:
 - aemake gmake

build_script:
  - cmd: C:/mingw-w64/x86_64-6.3.0-posix-seh-rt_v5-rev1/mingw32-make

artifacts:
  - path: "*.zip"
    name: Releases

deploy:
  description: '[Beta] Release.'
  force_update: true
  prerelease: false
  provider: GitHub
  auth_token:
    secure: KyPzEsLVrgHG6Gqf0eYoVgUx8QJo2HMhQkJBzZvndDASItHx4J8fJ1TFTuemJMf7
  artifact: Releases
  on:
    appveyor_repo_tag: true